name: tubes_money_management
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  awesome_snackbar_content: ^0.1.3
  build_runner: ^2.4.7
  cupertino_icons: ^1.0.6
  flutter_expanded_tile: ^0.3.7
  flutter_slidable: ^3.0.1
  flutter_svg: ^2.0.9
  flutter_tab_indicator_styler: ^2.0.0
  flutter_toggle_tab: ^1.4.1
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  lottie: ^2.7.0
  month_year_picker: ^0.3.0+1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  vertical_percent_indicator: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/image/money-removebg-preview.png
    - assets/image/plan.jpg
    - assets/image/incom.jpg
    - assets/image/expenss.jpg
    - assets/image/bag - Copy.jpg
    - assets/image/food.jpg
    - assets/image/list.jpg
    - assets/image/monlogo.jpg
    - assets/image/travel .jpg
    - assets/image/logout.jpg
    - assets/image/plan-removebg-preview.png
    - assets/image/category.webp
    - assets/image/icon.png
    - assets/image/medical_edited.jpg
    - assets/image/shopping_edited.jpg
    - assets/image/nosearchresultsanimation.json
    - assets/image/nodata.json

flutter_icons:
  image_path: "assets/image/logo.jpg"
  android: true
  ios: true
